lazo/core/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    #home page
    url(r'^$', views.home, name='home'),

    #page to show all topics
    url(r'^topics/$', views.topics, name="topics"),

    #url for a single topic
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name="topic")


]

lazo/lazo/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('core.urls', namespace="core")),
    
]

lazo/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from time import time 
from datetime import datetime, timedelta, tzinfo
# Create your models here.

class Topic(models.Model):
    text = models.CharField(max_length=200)
    dateTime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Entry(models.Model):

    topic = models.ForeignKey(Topic)
    text = models.TextField(default='')
    dateTime = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural = 'Entries'

    def __str__(self):
        return self.text[:50] + "..."

        
    

lazo/core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from .models import Topic, Entry

# Create your views here.

def home(request):
    return render(request, 'core/home.html')

def topics(request):
    #show all topics

    topics = Topic.objects.order_by('dateTime')
    context = {'topics':topics}

    return render(request, 'core/topics.html', context)



def topic(request, topic_id):

    #show an entry of a topic

    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-dateTime')
    context = {'topic':topic, 'entries': entries}
    return render(request, 'core/topic.html', context)

lazo/core/templates/core/base.html
<!DOCTYPE html>
<html>
    <body>
        <p>
            <a href="{% url 'core:home' %}"> Home</a> 
            <a href="{% url 'core:topics' %}"> Topics </a>
        </p>
    </body>
</html>


{%block content%} {%endblock content%}

lazo/core/templates/core/home.html
{%extends "core/base.html"%}

{%block content%}

<!DOCTYPE html>
<html> WTH is happening </html>
    <body>
        <h2>
            New Homepage data
        </h2>
        <p>
            This app helps you to keep track of your learning.
        </p>
    </body>


{%endblock content%}

lazo/core/templates/core/topic.html
{% extends "core/base.html" %}

{%block content%}

<p> Topic: {{Topic}}</p>

<p> Entries: </p>

<ul>
    {% for entry in entries %}

    <li>
        <p> {{entry.dateTime }} </p>
        <p> {{entry.text|linebreaks}} </p>
    </li>

    {%empty%}

    <li>
        There are no entries for this topic yet.
    </li>

    {% endfor %}

</ul>

{% endblock content %}

lazo/core/templates/core/topics.html
{%extends "core/base.html" %}

{%block content%}

<p>Topics</p>

<ul>
    {% for topic in topics %}
        <li>
           <a href="{% url 'core:topic' topic.id %}">{{topic}}</a> 
        </li>
    {% empty %}

        <li> No topics added yet</li>

    {%endfor%}

</ul>

{%endblock content%}